### PR TITLE
Refactoring

### LINKED ISSUE #6: Not adding LoadModule statement when not already present in httpd.conf
If there is no existing _LoadModule_ statement in httpd.conf for the PHP version being switched to, the script does not add it. This results in a non-functional web server, which is unable to interpret PHP.

The script does have a function to cover that scenario, but it's not working as expected because it is is relying on the existence of a "native osx" module in httpd.conf as the reference point to add the missing PHP module. When this line does not exist in the file (which is the case with macOS 13), then the LoadModule line is never added.

### PR DESCRIPTION
**Pull request by dregad**
Well I know I opened #4 asking if it was OK to do before I actually did it, but I went ahead anyway 😉. Hopefully this will be acceptable for you. 

I tested it on my mac (Ventura) and found no issues so far.

Note: this also fixes #6

### CODE REVIEW

**Comment by rhukster** [comment]
Cheers! will take a look this weekend.

**Comment by toddlahman** [comment]
One of my older MacBook Pros still uses MacOS Catalina. The Brew restart of Apache does not work, however, `sudo apachectl -k restart` does work. I have to manually restart Apache after the script finishes.

**Comment by dregad** [comment]
> The Brew restart of Apache does not work,

Was it working before I changed it to a single *brew services restart* ?

**Comment by toddlahman** [comment]
@dregad No. The ...
```
     brew services stop httpd
     brew services start httpd
```
also did not work before this new pull request on MacOS Catalina.

**Comment by rhukster** [comment]
> @dregad No. The ...
> 
> ```
>      brew services stop httpd
>      brew services start httpd
> ```
> 
> also did not work before this new pull request on MacOS Catalina.

This is not an issue with the script, it's related to your setup specfiically.   Those commands work fine withougt sudo for me and most people because the httpd process is being run as the user account. As soon as you run with `sudo` even once, the lock files and temp files and any other files that apache writes, become owned by root, and then your user  account will never be able to remove or rewrite them, hence it fails.  You have to remove all those root-owned files, then it will work fine.

**Comment by toddlahman** [comment]
On my OS I have both the Apple version of Apache installed, and the Homebrew version installed. I have both to be able to use more current versions of PHP on MacOS Catalina. Since it is not possible for the script to know how the user has Apache setup, and which version is configured to run the httpd service, the script may need to use a command that works for both. The command `apachectl -k restart` works with Homebrew, the Mac version of Apache, or any other installation of Apache. Homebrew is moving to only support Apple Silicone versions, which means the script will stop being backward compatible with more common commands that work with Homebrew or any other installation, due to the unpredictable configurations such as my own. Just a suggestion. I can always write my own script that works for Homebrew installs or non-Homebrew installs so the Apache PHP switching works for any Apache + PHP installation, but since the effort is to improve this script on the next iteration this seemed like the appropriate time to make this suggestion. To me the best approach is to use something that always works no matter how the user configuration is setup. After all, it is not uncommon for a user to have the Apple OS reinstall Apache on the next OS upgrade, and find the Homebrew command to restart the httpd service stopped working. If `apachectl -k restart` is used the user will never see this issue, and it won't matter if the user has the Apple version of Apache or the Homebrew version of Apache configured to run.

Below is a summary of the `apachectl` command used on systems where `apachectl` is always the command used in every configuration, and only the command location in the file system differs.

### Internal (MacOS version) Apache

- **Binary:** /usr/sbin/httpd
- **Start/Stop:** sudo /usr/sbin/apachectl start
- **Version:** /usr/sbin/apachectl -v
- **Config:** /etc/apache2/httpd.conf

### Homebrew Apache

- **Binary:** /usr/local/bin/httpd (symlink to ../Cellar/httpd)
- **Start/Stop:** sudo /usr/local/bin/apachectl start
- **Version:** /usr/local/bin/apachectl -v
- **Config:** /usr/local/etc/httpd/httpd.conf

### Homebrew Apache (Apple Silicon)
substitute /opt/homebrew for /usr/local in the group directly above. for example

- **Binary:** /opt/homebrew/bin/httpd (symlink to ../Cellar/httpd)
- **Start/Stop:** sudo /opt/homebrew/bin/apachectl start
- **Version:** /opt/homebrew/bin/apachectl -v
- **Config:** /opt/homebrew/etc/httpd/httpd.conf

**Comment by dregad** [comment]
It would probably be best to take this discussion on how to restart Apache to a separate issue, as it's somewhat off-topic.

**Comment by rhukster** [comment]
As I am working on the Sonoma update, i actually had chance to review and test this PR. Thanks so much working well for me.

**Pull request merged**
